In [ ]:
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_excel(
    r"C:\Users\SHALINI THANGAVEL\OneDrive\Desktop\Cart Abandonment Analysis Survey (Responses).xlsx"
)

In [ ]:
df.head()

,Timestamp,Your Name,Age Group,Gender,How often do you shop online?,Which shopping app do you use the most?,Have you ever added a product to your cart ?,Did you purchase the product which is added to the cart?,What are the reasons for abandoning your cart?,Does discount/free shipping encourage you to buy the product?,Is a simple checkout process important to complete your purchase?,Do reminder notifications help you return to complete your purchase?,Please share any suggestions to improve the online shopping experience:,Please share any suggestions to improve the online shopping experience: 2,Did you purchase the product which is added to the cart? 2,Did you purchase the product which is added to the cart? 3
0,2025-12-10 12:53:38.125,Rakshith,18 – 24 years,Male,Sometimes,Myntra,Yes,No,Product price too high,Yes,Yes,Yes,improve the product details,NaN,NaN,NaN
1,2025-12-10 20:59:04.336,Rithikkesh B,18 – 24 years,Male,Frequently,"Amazon, Flipkart, Myntra, Ajio",Yes,No,"Product price too high, Extra delivery charges...",Yes,Yes,Yes,Needs to improve customer support,NaN,NaN,NaN
2,2025-12-12 10:47:37.252,Sangamithra S,18 – 24 years,Female,Frequently,"Flipkart, Ajio",Yes,No,"Just browsing, Changed mind",Yes,Yes,Yes,NaN,NaN,NaN,NaN
3,2025-12-12 10:48:52.486,Subhagini,18 – 24 years,Female,Sometimes,"Amazon, Flipkart",Yes,Sometimes,"Checkout takes too long, Delivery time too lon...",Sometimes,Yes,Sometimes,-,-,NaN,NaN
4,2025-12-12 10:50:37.083,THARIKA THAHASIN S,18 – 24 years,Female,Sometimes,"Amazon, Flipkart, Myntra",Yes,No,Product price too high,Yes,Yes,Yes,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(200, 16)

In [ ]:
df.columns

Index(['Timestamp', 'Your Name ', '  Age Group  ', '   Gender  ',
       '  How often do you shop online?  ',
       '  Which shopping app do you use the most?  ',
       '  Have you ever added a product to your cart ? ',
       'Did you purchase the product which is added to the cart? ',
       'What are the reasons for abandoning your cart?  ',
       '  Does discount/free shipping encourage you to buy the product?  ',
       '  Is a simple checkout process important to complete your purchase?  ',
       '  Do reminder notifications help you return to complete your purchase?  ',
       'Please share any suggestions to improve the online shopping experience:',
       'Please share any suggestions to improve the online shopping experience: 2',
       'Did you purchase the product which is added to the cart?  2',
       'Did you purchase the product which is added to the cart?  3'],
      dtype='object')

In [ ]:
df.rename(columns={
    "Timestamp": "Timestamp",
    "Your Name ": "Name",
    "Age Group ": "Age_Group",
    "Gender ": "Gender",
    "How often do you shop online? ": "Online_Shopping_Frequency",
    "Which shopping app do you use the most? ": "Preferred_Shopping_App",
    "Have you ever added a product to your cart ? ": "Added_To_Cart",
    "Did you purchase the product which is added to the cart? ": "Purchase_Status",
    "What are the reasons for abandoning your cart? ": "Abandonment_Reason",
    "Does discount/free shipping encourage you to buy the product? ": "Discount_Influence",
    "Is a simple checkout process important to complete your purchase? ": "Checkout_Importance",
    "Do reminder notifications help you return to complete your purchase? ": "Reminder_Notification_Help",
    "Please share any suggestions to improve the online shopping experience": "Suggestions_1",
    "Please share any suggestions to improve the online shopping experience 2": "Suggestions_2",
    "Did you purchase the product which is added to the cart? 2": "Purchase_Status_2",
    "Did you purchase the product which is added to the cart? 3": "Purchase_Status_3"
}, inplace=True)

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
df.columns

Index(['Timestamp', 'Name', 'Age Group', 'Gender',
       'How often do you shop online?',
       'Which shopping app do you use the most?',
       'Have you ever added a product to your cart ?', 'Purchase_Status',
       'What are the reasons for abandoning your cart?',
       'Does discount/free shipping encourage you to buy the product?',
       'Is a simple checkout process important to complete your purchase?',
       'Do reminder notifications help you return to complete your purchase?',
       'Please share any suggestions to improve the online shopping experience:',
       'Please share any suggestions to improve the online shopping experience: 2',
       'Did you purchase the product which is added to the cart?  2',
       'Did you purchase the product which is added to the cart?  3'],
      dtype='object')

In [ ]:
df.rename(columns={
    "Timestamp": "Timestamp",
    "Your Name": "Name",
    "Age Group": "Age_Group",
    "Gender": "Gender",
    "How often do you shop online?": "Online_Shopping_Frequency",
    "Which shopping app do you use the most?": "Preferred_Shopping_App",
    "Have you ever added a product to your cart ?": "Added_To_Cart",
    "Did you purchase the product which is added to the cart?": "Purchase_Status",
    "What are the reasons for abandoning your cart?": "Abandonment_Reason",
    "Does discount/free shipping encourage you to buy the product?": "Discount_Influence",
    "Is a simple checkout process important to complete your purchase?": "Checkout_Importance",
    "Do reminder notifications help you return to complete your purchase?": "Reminder_Notification_Help",
    "Please share any suggestions to improve the online shopping experience": "Suggestions_1",
    "Please share any suggestions to improve the online shopping experience 2": "Suggestions_2",
    "Did you purchase the product which is added to the cart? 2": "Purchase_Status_2",
    "Did you purchase the product which is added to the cart? 3": "Purchase_Status_3"
}, inplace=True)

In [ ]:
df.columns

Index(['Timestamp', 'Name', 'Age_Group', 'Gender', 'Online_Shopping_Frequency',
       'Preferred_Shopping_App', 'Added_To_Cart', 'Purchase_Status',
       'Abandonment_Reason', 'Discount_Influence', 'Checkout_Importance',
       'Reminder_Notification_Help',
       'Please share any suggestions to improve the online shopping experience:',
       'Please share any suggestions to improve the online shopping experience: 2',
       'Did you purchase the product which is added to the cart?  2',
       'Did you purchase the product which is added to the cart?  3'],
      dtype='object')

In [ ]:
df.rename(columns={
    "Please share any suggestions to improve the online shopping experience:": "Suggestions_1",
    "Please share any suggestions to improve the online shopping experience: 2": "Suggestions_2",
    "Did you purchase the product which is added to the cart? 2": "Purchase_Status_2",
    "Did you purchase the product which is added to the cart? 3": "Purchase_Status_3"
}, inplace=True)

In [ ]:
df.columns

Index(['Timestamp', 'Name', 'Age_Group', 'Gender', 'Online_Shopping_Frequency',
       'Preferred_Shopping_App', 'Added_To_Cart', 'Purchase_Status',
       'Abandonment_Reason', 'Discount_Influence', 'Checkout_Importance',
       'Reminder_Notification_Help', 'Suggestions_1', 'Suggestions_2',
       'Did you purchase the product which is added to the cart?  2',
       'Did you purchase the product which is added to the cart?  3'],
      dtype='object')

In [ ]:
df = df.iloc[:, :-2]

In [ ]:
df.columns

Index(['Timestamp', 'Name', 'Age_Group', 'Gender', 'Online_Shopping_Frequency',
       'Preferred_Shopping_App', 'Added_To_Cart', 'Purchase_Status',
       'Abandonment_Reason', 'Discount_Influence', 'Checkout_Importance',
       'Reminder_Notification_Help', 'Suggestions_1', 'Suggestions_2'],
      dtype='object')

In [ ]:
df.isnull().sum()

Timestamp                      0
Name                           0
Age_Group                      0
Gender                         0
Online_Shopping_Frequency      0
Preferred_Shopping_App         0
Added_To_Cart                  0
Purchase_Status                0
Abandonment_Reason            58
Discount_Influence            58
Checkout_Importance           58
Reminder_Notification_Help    58
Suggestions_1                 67
Suggestions_2                 13
dtype: int64

In [ ]:
df["Abandonment_Reason"] = df["Abandonment_Reason"].fillna("Not Applicable")

In [ ]:
df["Discount_Influence"] = df["Discount_Influence"].fillna("Not Answered")
df["Checkout_Importance"] = df["Checkout_Importance"].fillna("Not Answered")
df["Reminder_Notification_Help"] = df["Reminder_Notification_Help"].fillna("Not Answered")

df["Suggestions_1"] = df["Suggestions_1"].fillna("No suggestion")
df["Suggestions_2"] = df["Suggestions_2"].fillna("No suggestion")

df["Suggestions_1"] = df["Suggestions_1"].replace("-", "Not Answered")
df["Suggestions_2"] = df["Suggestions_2"].replace("-", "Not Answered")

In [ ]:

df.isnull().sum()
df["Suggestions_1"].value_counts()

Suggestions_1
No suggestion                67
Nothing                      12
No                            5
Not Answered                  5
na                            4
                             ..
No suggestion                 1
Personalized offers           1
Not bad                       1
More discount                 1
Negative customer reviews     1
Name: count, Length: 102, dtype: int64

In [ ]:
df["Abandonment_Reason"] = df["Abandonment_Reason"].str.lower()

In [ ]:
df["Abandonment_Reason"] = df["Abandonment_Reason"].str.strip()

In [ ]:
df["Abandonment_Reason"] = df["Abandonment_Reason"].replace({
    "price is high": "high price",
    "too costly": "high price",
    "costly": "high price",
    "delivery charges are high": "high delivery charge",
    "delivery charge high": "high delivery charge",
    "payment issue": "payment problem",
    "payment failure": "payment problem",
    "checkout process is long": "complex checkout"
})

In [ ]:
df["Abandonment_Reason"].value_counts()

Abandonment_Reason
not applicable                                                                                                                                     58
product price too high                                                                                                                             13
product price too high, extra delivery charges                                                                                                     12
delivery time too long                                                                                                                             12
changed mind                                                                                                                                        8
just browsing                                                                                                                                       7
extra delivery charges                                                                                                                              6
product price too high, delivery time too long                                                                                                      6
product price too high, extra delivery charges, delivery time too long                                                                              5
just browsing, changed mind                                                                                                                         4
delivery time too long, changed mind                                                                                                                4
checkout takes too long, app or website technical problem                                                                                           3
payment issues                                                                                                                                      3
checkout takes too long, delivery time too long                                                                                                     3
extra delivery charges, just browsing, changed mind                                                                                                 2
payment issues, changed mind                                                                                                                        2
checkout takes too long, delivery time too long, changed mind                                                                                       2
payment issues, checkout takes too long                                                                                                             2
payment issues, app or website technical problem                                                                                                    2
app or website technical problem, delivery time too long, changed mind                                                                              2
product price too high, extra delivery charges, checkout takes too long                                                                             2
product price too high, extra delivery charges, payment issues                                                                                      2
extra delivery charges, checkout takes too long, delivery time too long                                                                             2
payment issues, just browsing, delivery time too long                                                                                               2
product price too high, just browsing, changed mind                                                                                                 2
product price too high, extra delivery charges, just browsing, changed mind                                                                         2
extra delivery charges, changed mind                                                                                                                2
product price too high, extra delivery charges, delivery time too long, changed mind                                                                2
product price too high, app or website technical problem, delivery time too long, changed mind                                                      1
product out of stock at checkout                                                                                                                    1
extra delivery charges, long delivery time                                                                                                          1
payment issues, easy cancellation                                                                                                                   1
app or website technical problem                                                                                                                    1
better product image                                                                                                                                1
extra delivery charges, payment issues, delivery time too long                                                                                      1
product price too high, checkout takes too long                                                                                                     1
extra delivery charges, payment issues                                                                                                              1
checkout takes too long, return takes too long                                                                                                      1
product price too high, extra delivery charges, checkout takes too long, app or website technical problem, delivery time too long, changed mind     1
extra delivery charges, payment issues, checkout takes too long, app or website technical problem, delivery time too long                           1
app or website technical problem, delivery time too long                                                                                            1
just browsing, delivery time too long                                                                                                               1
extra delivery charges, just browsing                                                                                                               1
payment issues, checkout takes too long, delivery time too long                                                                                     1
extra delivery charges, app or website technical problem                                                                                            1
checkout takes too long                                                                                                                             1
product price too high, just browsing, delivery time too long, changed mind                                                                         1
extra delivery charges, delivery time too long, changed mind                                                                                        1
extra delivery charges, payment issues, changed mind                                                                                                1
extra delivery charges, delivery time too long                                                                                                      1
payment issues, delivery time too long                                                                                                              1
payment issues, app or website technical problem, delivery time too long                                                                            1
extra delivery charges, checkout takes too long, delivery time too long, changed mind                                                               1
product price too high, extra delivery charges, changed mind                                                                                        1
product price too high, extra delivery charges, just browsing                                                                                       1
negative customer reviews                                                                                                                           1
Name: count, dtype: int64

In [ ]:
def categorize_reason(reason):
    if "price" in reason:
        return "Price Issue"
    elif "delivery charges" in reason:
        return "Delivery Cost Issue"
    elif "delivery time" in reason:
        return "Delivery Time Issue"
    elif "payment" in reason:
        return "Payment Issue"
    elif "checkout" in reason:
        return "Checkout Issue"
    elif "technical" in reason or "app" in reason or "website" in reason:
        return "Technical Issue"
    elif "just browsing" in reason:
        return "Browsing Behavior"
    elif "changed mind" in reason:
        return "User Decision"
    else:
        return "Other"

In [ ]:
df["Reason_Category"] = df["Abandonment_Reason"].apply(categorize_reason)

In [ ]:
df["Reason_Category"].value_counts()

Reason_Category
Technical Issue        59
Price Issue            52
Delivery Time Issue    30
Delivery Cost Issue    22
Browsing Behavior      11
Payment Issue          10
User Decision           8
Checkout Issue          6
Other                   2
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.to_excel("Cleaned_Cart_Abandonment_Data.xlsx", index=False)

In [ ]:
df.sample(10)

,Timestamp,Name,Age_Group,Gender,Online_Shopping_Frequency,Preferred_Shopping_App,Added_To_Cart,Purchase_Status,Abandonment_Reason,Discount_Influence,Checkout_Importance,Reminder_Notification_Help,Suggestions_1,Suggestions_2,Reason_Category
10,2025-12-12 20:41:12.508,Anish Fathima Z,18 – 24 years,Female,Frequently,"Amazon, Flipkart, Meesho, Nykaa",Yes,No,"just browsing, delivery time too long",Yes,Yes,Yes,Not Answered,Not Answered,Delivery Time Issue
173,2025-12-28 21:42:47.367,Dinesh Kumar M,18 – 24 years,Male,Frequently,"Amazon, Flipkart, Ajio",Yes,Sometimes,changed mind,No,Yes,Sometimes,The biggest issue for giant marketplaces right...,The biggest issue for giant marketplaces right...,User Decision
48,2025-12-14 11:06:07.088,Padmashini,18 – 24 years,Female,Sometimes,"Amazon, Flipkart, Meesho",Yes,No,"product price too high, extra delivery charges...",Yes,Yes,Sometimes,No suggestion,No suggestion,Price Issue
101,2025-12-16 15:01:07.567,Vishmaya.S,18 – 24 years,Female,Sometimes,"Amazon, Flipkart, Meesho, Ajio",No,Sometimes,delivery time too long,Sometimes,Yes,Yes,No suggestion,No suggestion,Delivery Time Issue
71,2025-12-16 12:37:01.497,Nishanth. T,18 – 24 years,Male,Sometimes,"Amazon, Flipkart, Myntra",Yes,Sometimes,"product price too high, extra delivery charges...",Yes,Yes,Yes,Need to improve customer service,Need to improve customer service,Price Issue
22,2025-12-12 21:21:10.861,Dharun MR,18 – 24 years,Male,Rarely,"Amazon, Flipkart",Yes,No,"product price too high, just browsing, deliver...",Yes,Yes,No,Nil,Community for product related questions before...,Price Issue
193,2026-01-03 11:08:03.915,Yuvaraj,25 – 34 years,Male,Sometimes,"Amazon, Flipkart",Yes,Sometimes,"product price too high, extra delivery charges",Yes,Yes,Sometimes,Offer price-drop alerts,Offer price-drop alerts,Price Issue
91,2025-12-16 14:59:50.594,Ashwin,18 – 24 years,Male,Sometimes,Amazon,Yes,Yes,not applicable,Not Answered,Not Answered,Not Answered,No suggestion,To avoid used and damaged product,Technical Issue
128,2025-12-17 10:13:27.326,Elakkiya Varshini.R.,18 – 24 years,Female,Frequently,"Amazon, Flipkart, Ajio",Yes,Yes,not applicable,Not Answered,Not Answered,Not Answered,No suggestion,Nothing,Technical Issue
13,2025-12-12 20:46:04.970,Dharaneesh S,18 – 24 years,Male,Frequently,"Flipkart, Myntra, Ajio",Yes,No,"product price too high, delivery time too long",Yes,Yes,Sometimes,Flexible delivery,Product reviews,Price Issue

In [ ]:
import os
os.getcwd()

'C:\\Users\\SHALINI THANGAVEL'

In [ ]:
df.to_excel("FINAL_Cleaned_Cart_Abandonment_Data.xlsx", index=False)

In [ ]:
# Data Analysis & Visualization

In [ ]:
df.head()

,Timestamp,Name,Age_Group,Gender,Online_Shopping_Frequency,Preferred_Shopping_App,Added_To_Cart,Purchase_Status,Abandonment_Reason,Discount_Influence,Checkout_Importance,Reminder_Notification_Help,Suggestions_1,Suggestions_2,Reason_Category
0,2025-12-10 12:53:38.125,Rakshith,18 – 24 years,Male,Sometimes,Myntra,Yes,No,product price too high,Yes,Yes,Yes,improve the product details,No suggestion,Price Issue
1,2025-12-10 20:59:04.336,Rithikkesh B,18 – 24 years,Male,Frequently,"Amazon, Flipkart, Myntra, Ajio",Yes,No,"product price too high, extra delivery charges...",Yes,Yes,Yes,Needs to improve customer support,No suggestion,Price Issue
2,2025-12-12 10:47:37.252,Sangamithra S,18 – 24 years,Female,Frequently,"Flipkart, Ajio",Yes,No,"just browsing, changed mind",Yes,Yes,Yes,No suggestion,No suggestion,Browsing Behavior
3,2025-12-12 10:48:52.486,Subhagini,18 – 24 years,Female,Sometimes,"Amazon, Flipkart",Yes,Sometimes,"checkout takes too long, delivery time too lon...",Sometimes,Yes,Sometimes,Not Answered,Not Answered,Delivery Time Issue
4,2025-12-12 10:50:37.083,THARIKA THAHASIN S,18 – 24 years,Female,Sometimes,"Amazon, Flipkart, Myntra",Yes,No,product price too high,Yes,Yes,Yes,No suggestion,No suggestion,Price Issue

In [ ]:
df.shape

(200, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timestamp                   200 non-null    datetime64[ns]
 1   Name                        200 non-null    object
 2   Age_Group                   200 non-null    object
 3   Gender                      200 non-null    object
 4   Online_Shopping_Frequency   200 non-null    object
 5   Preferred_Shopping_App      200 non-null    object
 6   Added_To_Cart               200 non-null    object
 7   Purchase_Status             200 non-null    object
 8   Abandonment_Reason          200 non-null    object
 9   Discount_Influence          200 non-null    object
 10  Checkout_Importance         200 non-null    object
 11  Reminder_Notification_Help  200 non-null    object
 12  Suggestions_1               200 non-null    object
 13  Suggestions_2               200 non-null    object
 14  Reason_Category             200 non-null    object
dtypes: datetime64[ns](1), object(14)
memory usage: 23.6+ KB

In [ ]:
df["Age_Group"].unique()
df["Age_Group"] = df["Age_Group"].replace({
    "18 - 24 years": "18 – 24 years"
})
df["Age_Group"].value_counts()

Age_Group
18 – 24 years    159
25 – 34 years     27
45+ years          8
35 – 44 years      5
Prajith Tk         1
Name: count, dtype: int64

In [ ]:
#Gender Distribution

In [ ]:
df["Gender"].value_counts()

Gender
Female    115
Male       85
Name: count, dtype: int64

In [ ]:
df["Online_Shopping_Frequency"].value_counts()

Online_Shopping_Frequency
Sometimes     106
Rarely         48
Frequently     43
Sometimes       1
Male            1
Never           1
Name: count, dtype: int64

In [ ]:
df["Purchase_Status"].value_counts()

Purchase_Status
Sometimes    80
No           62
Yes          58
Name: count, dtype: int64

In [ ]:
df["Abandonment_Reason"].value_counts()

Abandonment_Reason
not applicable                                                                                                                                     58
product price too high                                                                                                                             13
product price too high, extra delivery charges                                                                                                     12
delivery time too long                                                                                                                             12
changed mind                                                                                                                                        8
just browsing                                                                                                                                       7
extra delivery charges                                                                                                                              6
product price too high, delivery time too long                                                                                                      6
product price too high, extra delivery charges, delivery time too long                                                                              5
just browsing, changed mind                                                                                                                         4
delivery time too long, changed mind                                                                                                                4
checkout takes too long, app or website technical problem                                                                                           3
payment issues                                                                                                                                      3
checkout takes too long, delivery time too long                                                                                                     3
extra delivery charges, just browsing, changed mind                                                                                                 2
payment issues, changed mind                                                                                                                        2
checkout takes too long, delivery time too long, changed mind                                                                                       2
payment issues, checkout takes too long                                                                                                             2
payment issues, app or website technical problem                                                                                                    2
app or website technical problem, delivery time too long, changed mind                                                                              2
product price too high, extra delivery charges, checkout takes too long                                                                             2
product price too high, extra delivery charges, payment issues                                                                                      2
extra delivery charges, checkout takes too long, delivery time too long                                                                             2
payment issues, just browsing, delivery time too long                                                                                               2
product price too high, just browsing, changed mind                                                                                                 2
product price too high, extra delivery charges, just browsing, changed mind                                                                         2
extra delivery charges, changed mind                                                                                                                2
product price too high, extra delivery charges, delivery time too long, changed mind                                                                2
product price too high, app or website technical problem, delivery time too long, changed mind                                                      1
product out of stock at checkout                                                                                                                    1
extra delivery charges, long delivery time                                                                                                          1
payment issues, easy cancellation                                                                                                                   1
app or website technical problem                                                                                                                    1
better product image                                                                                                                                1
extra delivery charges, payment issues, delivery time too long                                                                                      1
product price too high, checkout takes too long                                                                                                     1
extra delivery charges, payment issues                                                                                                              1
checkout takes too long, return takes too long                                                                                                      1
product price too high, extra delivery charges, checkout takes too long, app or website technical problem, delivery time too long, changed mind     1
extra delivery charges, payment issues, checkout takes too long, app or website technical problem, delivery time too long                           1
app or website technical problem, delivery time too long                                                                                            1
just browsing, delivery time too long                                                                                                               1
extra delivery charges, just browsing                                                                                                               1
payment issues, checkout takes too long, delivery time too long                                                                                     1
extra delivery charges, app or website technical problem                                                                                            1
checkout takes too long                                                                                                                             1
product price too high, just browsing, delivery time too long, changed mind                                                                         1
extra delivery charges, delivery time too long, changed mind                                                                                        1
extra delivery charges, payment issues, changed mind                                                                                                1
extra delivery charges, delivery time too long                                                                                                      1
payment issues, delivery time too long                                                                                                              1
payment issues, app or website technical problem, delivery time too long                                                                            1
extra delivery charges, checkout takes too long, delivery time too long, changed mind                                                               1
product price too high, extra delivery charges, changed mind                                                                                        1
product price too high, extra delivery charges, just browsing                                                                                       1
negative customer reviews                                                                                                                           1
Name: count, dtype: int64

In [ ]:
df["Abandonment_Reason"] = df["Abandonment_Reason"].str.lower()

In [ ]:
# Split by comma
reasons_split = df["Abandonment_Reason"].str.split(",")

# Convert list into rows
reasons_exploded = reasons_split.explode()

In [ ]:
reasons_exploded = reasons_exploded.str.strip()

In [ ]:
reasons_exploded = reasons_exploded[reasons_exploded != "not applicable"]

In [ ]:
reason_counts = reasons_exploded.value_counts()
print(reason_counts)

Abandonment_Reason
delivery time too long              53
product price too high              52
extra delivery charges              50
changed mind                        39
just browsing                       23
payment issues                      21
checkout takes too long             21
app or website technical problem    14
return takes too long                1
better product image                 1
easy cancellation                    1
long delivery time                   1
product out of stock at checkout     1
negative customer reviews            1
Name: count, dtype: int64

In [ ]:
#Age vs Purchase
pd.crosstab(df["Age_Group"], df["Purchase_Status"])

Purchase_Status  No  Sometimes  Yes
Age_Group
18 – 24 years    55         54   50
25 – 34 years     4         18    5
35 – 44 years     1          4    0
45+ years         2          4    2
Prajith Tk        0          0    1

In [ ]:
#Gender vs Purchase
pd.crosstab(df["Gender"], df["Purchase_Status"])

Purchase_Status  No  Sometimes  Yes
Gender
Female           36         49   30
Male             26         31   28

In [ ]:
#Purchase vs Abandonment

df["Purchase_Status"].value_counts()

Purchase_Status
Sometimes    80
No           62
Yes          58
Name: count, dtype: int64

In [ ]:
#percentage 

purchase_counts = df["Purchase_Status"].value_counts()

purchase_percentage = (purchase_counts / purchase_counts.sum()) * 100

print(purchase_percentage.round(2))

Purchase_Status
Sometimes    40.0
No           31.0
Yes          29.0
Name: count, dtype: float64

In [ ]:
abandon_rate = purchase_percentage.get("No", 0)
print("Cart Abandonment Rate:", round(abandon_rate, 2), "%")

Cart Abandonment Rate: 31.0 %

In [ ]:
def categorize_reason(reason):
    reason = str(reason).lower()
    
    if "price" in reason or "cost" in reason:
        return "Price Issue"
    elif "delivery" in reason or "shipping" in reason:
        return "Delivery Issue"
    elif "payment" in reason:
        return "Payment Issue"
    elif "checkout" in reason:
        return "Checkout Issue"
    elif "browse" in reason or "later" in reason:
        return "Browsing Behavior"
    else:
        return "Other"

In [ ]:
df["Reason_Category"] = df["Abandonment_Reason"].apply(categorize_reason)

In [ ]:
df["Reason_Category"].value_counts()

Reason_Category
Other             80
Price Issue       52
Delivery Issue    52
Payment Issue     10
Checkout Issue     6
Name: count, dtype: int64

In [ ]:
#app preferred
df["Preferred_Shopping_App"].value_counts().head(10)

Preferred_Shopping_App
Amazon, Flipkart                    26
Flipkart                            24
Amazon, Flipkart, Meesho            22
Meesho                              17
Amazon                              16
Flipkart, Meesho                    10
Amazon, Flipkart, Ajio               8
Amazon, Flipkart, Myntra             7
Flipkart, Ajio                       6
Amazon, Flipkart, Myntra, Meesho     6
Name: count, dtype: int64

In [ ]:
df["Preferred_Shopping_App"] = df["Preferred_Shopping_App"].str.lower()
apps_split = df["Preferred_Shopping_App"].str.split(",")
apps_exploded = apps_split.explode()
apps_exploded = apps_exploded.str.strip()
app_counts = apps_exploded.value_counts()
print(app_counts)

Preferred_Shopping_App
flipkart            136
amazon              112
meesho               76
ajio                 48
myntra               44
nykaa                20
shopsy                1
offline shopping      1
purple                1
first cry             1
Name: count, dtype: int64

In [ ]:
# Convert Series to DataFrame
app_counts_df = app_counts.reset_index()

# Rename columns
app_counts_df.columns = ["App_Name", "User_Count"]

# Save to Excel
app_counts_df.to_excel("App_Usage_Count.xlsx", index=False)

In [ ]:
#age vs abondenment

In [ ]:
age_abandon = pd.crosstab(df["Age_Group"], df["Purchase_Status"])
print(age_abandon)

Purchase_Status  No  Sometimes  Yes
Age_Group
18 – 24 years    55         54   50
25 – 34 years     4         18    5
35 – 44 years     1          4    0
45+ years         2          4    2
Prajith Tk        0          0    1

In [ ]:
# Convert to percentage
age_abandon_percent = age_abandon.div(age_abandon.sum(axis=1), axis=0) * 100
print(age_abandon_percent.round(2))

Purchase_Status     No  Sometimes     Yes
Age_Group
18 – 24 years    34.59      33.96   31.45
25 – 34 years    14.81      66.67   18.52
35 – 44 years    20.00      80.00    0.00
45+ years        25.00      50.00   25.00
Prajith Tk        0.00       0.00  100.00

In [ ]:
# gender vs abondenment

In [ ]:
gender_abandon = pd.crosstab(df["Gender"], df["Purchase_Status"])
print(gender_abandon)

Purchase_Status  No  Sometimes  Yes
Gender
Female           36         49   30
Male             26         31   28

In [ ]:
gender_abandon_percent = gender_abandon.div(gender_abandon.sum(axis=1), axis=0) * 100
print(gender_abandon_percent.round(2))

Purchase_Status     No  Sometimes    Yes
Gender
Female           31.30      42.61  26.09
Male             30.59      36.47  32.94

In [ ]:
#Risk score

In [ ]:
# Function to calculate risk score
def calculate_risk(row):
    score = 0
    
    # Purchase behavior
    if row["Purchase_Status"] == "No":
        score += 3
    elif row["Purchase_Status"] == "Sometimes":
        score += 2
    
    # Shopping frequency
    if row["Online_Shopping_Frequency"] == "Rarely":
        score += 2
    elif row["Online_Shopping_Frequency"] == "Sometimes":
        score += 1
    
    # Abandonment reason (price/delivery related)
    reason = str(row["Abandonment_Reason"]).lower()
    if "price" in reason or "delivery" in reason:
        score += 1
    
    return score

In [ ]:
df["Risk_Score"] = df.apply(calculate_risk, axis=1)

In [ ]:
df[["Purchase_Status", "Online_Shopping_Frequency", "Risk_Score"]].head()

  Purchase_Status Online_Shopping_Frequency  Risk_Score
0              No                Sometimes            4
1              No                Frequently           4
2              No                Frequently           3
3       Sometimes                 Sometimes           4
4              No                 Sometimes           5

In [ ]:
def risk_level(score):
    if score >= 4:
        return "High Risk"
    elif score >= 2:
        return "Medium Risk"
    else:
        return "Low Risk"

df["Risk_Level"] = df["Risk_Score"].apply(risk_level)

In [ ]:
df["Risk_Level"].value_counts()

Risk_Level
High Risk      112
Medium Risk     44
Low Risk        44
Name: count, dtype: int64

In [ ]:
# Save updated dataset with Risk columns
df.to_excel("FINAL_Cart_Abandonment_With_Risk.xlsx", index=False)

In [ ]:
# Assume average cart value
avg_cart_value = 1000

In [ ]:
# Count abandoned customers
abandoned_count = df[df["Purchase_Status"] == "No"].shape[0]

# Total revenue loss
total_loss = abandoned_count * avg_cart_value

print("Total Abandoned Customers:", abandoned_count)
print("Estimated Total Revenue Loss: ₹", total_loss)

Total Abandoned Customers: 62
Estimated Total Revenue Loss: ₹ 62000

In [ ]:
# Convert to lowercase
df["Abandonment_Reason"] = df["Abandonment_Reason"].str.lower()

# Split multiple reasons
reasons_split = df["Abandonment_Reason"].str.split(",")

# Convert list into separate rows
reasons_exploded = reasons_split.explode()

# Remove extra spaces
reasons_exploded = reasons_exploded.str.strip()

# Remove non-relevant values
reasons_exploded = reasons_exploded[reasons_exploded != "not applicable"]

In [ ]:
reason_counts = reasons_exploded.value_counts()

print(reason_counts.head(10))

Abandonment_Reason
delivery time too long              53
product price too high              52
extra delivery charges              50
changed mind                        39
just browsing                       23
payment issues                      21
checkout takes too long             21
app or website technical problem    14
return takes too long                1
better product image                 1
Name: count, dtype: int64

In [ ]:
loss_per_reason = reason_counts * avg_cart_value

print(loss_per_reason.head(10))

Abandonment_Reason
delivery time too long              53000
product price too high              52000
extra delivery charges              50000
changed mind                        39000
just browsing                       23000
payment issues                      21000
checkout takes too long             21000
app or website technical problem    14000
return takes too long                1000
better product image                 1000
Name: count, dtype: int64

In [ ]:
top3_loss = loss_per_reason.head(3)

print("Top 3 Reasons Causing Maximum Revenue Loss:")
print(top3_loss)

Top 3 Reasons Causing Maximum Revenue Loss:
Abandonment_Reason
delivery time too long    53000
product price too high    52000
extra delivery charges    50000
Name: count, dtype: int64

In [ ]:
# Average cart value
avg_cart_value = 1000

# Total abandoned customers
abandoned_count = df[df["Purchase_Status"] == "No"].shape[0]

# Current loss
current_loss = abandoned_count * avg_cart_value

print("Current Revenue Loss: ₹", current_loss)

Current Revenue Loss: ₹ 62000

In [ ]:
# Possible improvement scenarios
reduction_rates = [0.10, 0.20, 0.30]

for rate in reduction_rates:
    saved_customers = int(abandoned_count * rate)
    saved_revenue = saved_customers * avg_cart_value
    
    print(f"If abandonment reduces by {int(rate*100)}%:")
    print("Recovered Customers:", saved_customers)
    print("Revenue Saved: ₹", saved_revenue)
    print("------")

If abandonment reduces by 10%:
Recovered Customers: 6
Revenue Saved: ₹ 6000
------
If abandonment reduces by 20%:
Recovered Customers: 12
Revenue Saved: ₹ 12000
------
If abandonment reduces by 30%:
Recovered Customers: 18
Revenue Saved: ₹ 18000
------

In [ ]:
df.columns

Index(['Timestamp', 'Name', 'Age_Group', 'Gender', 'Online_Shopping_Frequency',
       'Preferred_Shopping_App', 'Added_To_Cart', 'Purchase_Status',
       'Abandonment_Reason', 'Discount_Influence', 'Checkout_Importance',
       'Reminder_Notification_Help', 'Suggestions_1', 'Suggestions_2',
       'Reason_Category', 'Risk_Score', 'Risk_Level'],
      dtype='object')

In [ ]:
import os

# Check where file will be saved
print(os.getcwd())

# Save updated file
df.to_excel("FINAL_Data_With_Risk.xlsx", index=False)

print("File saved successfully!")

C:\Users\SHALINI THANGAVEL
File saved successfully!

In [ ]:
# Convert Series to DataFrame
loss_reason_df = loss_per_reason.reset_index()

# Rename columns
loss_reason_df.columns = ["Abandonment_Reason", "Revenue_Loss"]

# Save to Excel
loss_reason_df.to_excel("Loss_By_Reason.xlsx", index=False)

In [ ]:
summary_df = pd.DataFrame({
    "Metric": ["Total Abandoned Customers", "Total Revenue Loss"],
    "Value": [abandoned_count, current_loss]
})

summary_df.to_excel("Business_Summary.xlsx", index=False)

In [ ]:
reduction_rates = [0.10, 0.20, 0.30]

scenario_data = []

for rate in reduction_rates:
    saved_customers = int(abandoned_count * rate)
    saved_revenue = saved_customers * avg_cart_value
    
    scenario_data.append({
        "Reduction_Percentage": int(rate*100),
        "Recovered_Customers": saved_customers,
        "Revenue_Recovered": saved_revenue
    })

scenario_df = pd.DataFrame(scenario_data)

scenario_df.to_excel("Recovery_Scenarios.xlsx", index=False)